### PR TITLE
SWMM v5.1.15 Update

### PR DESCRIPTION
**Pull request by michaeltryby**
Proposed update

### CODE REVIEW

**Comment by LRossman** [comment]
Adding a '-' in intermediate blank columns of the Flow Summary table allows its contents to be parsed correctly when displayed in SWMM's GUI. The reg tests don't recognize this and cause some test cases to fail. Take Example3.inp for example. The previous build shows the following Flow Summary line for the the project's pump:
```
  -----------------------------------------------------------------------------
                                 Maximum  Time of Max   Maximum    Max/    Max/
                                  |Flow|   Occurrence   |Veloc|    Full    Full
  Link                 Type          CFS  days hr:min    ft/sec    Flow   Depth
  -----------------------------------------------------------------------------
  PUMP1                PUMP         0.64     0  09:53              0.71
```
while the new build has:
```
  PUMP1                PUMP         0.64     0  09:23         -    0.71
```
When the example is run under the GUI, the PUMP1 line in the table shows as follows:
```
  PUMP1                PUMP         0.64     0  09:23      0.71
```
where the Max/Full Flow value shows up in the Max. Velocity column. If we want to fix this bug we need to replace the .rpt files for the 12 test cases that failed.

**Comment by LRossman** [comment]
The failed reg tests for the fixes made to findNodeDepths in dynwave .c are likely due to the original code thinking that an Outfall node has failed to converge when in fact those nodes are always converged by definition. The updated code uses the correct logic for checking node convergence, whether or not multi-threading is used. Therefore the results for the regression test files should be updated by using the updated code to re-generate them.

**Comment by LRossman** [comment]
The "_Modifies format of Link Flow Summary table_" and "_Fix possible race condition in dynwave.c_" commits have been restored to the `lew-develop` branch so they can await an updating of the regression test benchmark files before being tested again.

**Comment by LRossman** [comment]
Just to clarify what this latest commit (2817609) does, it fixes the possible race condition in `dynwave.c` (issue #58) but removed the fix for the Link Flow Summary table (that caused results for non-conduit links to show up in the wrong columns (issue #36)) so that the reg tests could pass. To add the fix for #36 one only has to replace line 704 in `statsrpt.c` with:
```
char   nullValue = '-';
```
and regenerate the benchmark results for the regression test files.

**Comment by michaeltryby** [comment]
Commit 2e7814c reimplements the fix for Link Flow Summary Table #36. 
Benchmark files have been updated.

**Pull request closed without merging**
