### PR TITLE
Revision 8 of SWMM 5.2.0 from Lew 2/1/2022

### PR DESCRIPTION
**Pull request by michelleannesimon**
Lew repaired a few bugs based on Peer-Reviewers' comments.  This Version 8 is dated 2/1/2022.

### CODE REVIEW

**Comment by michelleannesimon** [comment]
@michaeltryby.  Please checkout this pull request.

**Comment by michaeltryby** [comment]
@michelleannesimon I'll have a look. Thanks!

**Comment by michelleannesimon** [comment]
@michaeltryby  Lew wants to commit directly to this repository and not through my michelleannesimon repository.  Please give me access rights.

**Comment by michaeltryby** [comment]
@michelleannesimon I don't have admin control of this repo. You need to talk to someone in OMS for that.

**Comment by michaeltryby** [comment]
@michelleannesimon As far as I know, Lew already has access.

**Comment by LRossman** [comment]
I lost my access because I wasn’t able to sign in to the User Profile form that was required to migrate accounts to the new EPA GH Enterprise system. I had no clue what my sign-in credentials were (my normal GitHub user name and password didn’t work). Anyway, I’m now out in the cold as far as the USEPA/Stormwater-Management-Model repo is concerned.

**Comment by michelleannesimon** [comment]
I think that EPA changed the way it handles Github.  Lew and I used to have write privileges. Everyone was supposed to fill out a form.  If a person did not fill out the form, that person seems to have lost privileges just this week.  EPA Github people gave me privileges yesterday and now I can write to this site.  I filled out the form for Lew (it has to be an EPA person to have access to the form) and can try to get his privileges back.

As you can see I loaded up version 8 of Lew's SWMM 5.2 yesterday.

**Comment by michelleannesimon** [comment]
Lew,
I can get you access again.

Michelle

**Comment by bemcdonnell** [comment]
@LRossman, I just checked and your account has had "write" access to OWA-SWMM since the beginning. We'd be happy to have you at OWA if you'd be interested!

**Comment by michelleannesimon** [comment]
Lew now has write access to this github site.

**Comment by LRossman** [comment]
@bemcdonnell  I believe I did make a small contribution to OWA-SWMM several years ago (see lrossman-dev). What OWA-SWMM needs now is to be updated to EPA-SWMM 5.2.0 (I think it's 2 or 3 versions behind). One impediment to this is that the automated regression testing will fail due to bug fixes that produce different (and more correct) results than contained in the benchmark files. We've already run into this with the new update on the EPA repo which uses the same test and benchmark files as OWA-SWMM. A new set of benchmark files needs to be generated before any merging of a 5.2.0 update can be made.

**Comment by bemcdonnell** [comment]
@LRossman, yeah that's a great point. I will raise the issue.  We will be working on updating the reg-tests using each USEPA-SWMM release. Moreover, we can set the OWA-SWMM step-versions to use the respective USEPA-SWMM testing artifacts.  Upgrading to 5.2 will be subtly more complicated since there is a separate API coming into existence.  We could easily collaborate on that over at OWA. There are offline talks about migrating to a cleaner and more friendly API design.  And beyond API and testing, we are also looking at some data model implementations to reduce large-model simulation time but hopefully an order of magnitude.  I'll raise the issues and see how soon we can get our releases caught up with your code.

**Pull request closed without merging**
