### PR TITLE
Update stats.c

### PR DESCRIPTION
**Pull request by LRossman**
Fixes failure to initialize GW final upper zone moisture content and final water table values producing strange summary results for 100% impervious subcatchments with GW.

### CODE REVIEW

**Comment by dickinsonre** [comment]
Thanks as always @LRossman I need to make a few examples of all of these cross processes.

**Comment by michaeltryby** [comment]
@LRossman I have a fix for Issue #53. The changes are confined to `stats.c`. If you don't mind I would like to append it to this PR. Sound good?

**Comment by michaeltryby** [comment]
@LRossman I pushed the commit so you can have a look at them.

**Comment by LRossman** [comment]
@michaeltryby I concur with the changes you made to `stats.c`.

**Comment by michaeltryby** [comment]
close #53

**Pull request merged**
