### PR TITLE
Speed updates to dwflow.c

### PR DESCRIPTION
**Pull request by swmm-js**
Increases speed of dwflow by replacing commonly used, expensive function with faster_pow_0_66666 and faster_pow_1_33333.

Added files:
altfuncs.c

Modified files:
globals.h
funcs.h
swmm5.c

### CODE REVIEW

**Comment by michaeltryby** [comment]
@swmm-js Thanks for the PR. What kind of performance improvement are you seeing with this optimization?

**Comment by LRossman** [comment]
@swmm-js you could also create a table lookup for the `exp(-pow(yNorm, 2.4)` term in the `getSlotWidth `function in dwflow.c. `yNorm `varies between 0.985257 and 1.78.

**Comment by swmm-js** [comment]
> @swmm-js Thanks for the PR. What kind of performance improvement are you seeing with this optimization?

This is between 3% and 7% for the 40-second to 2-minute runs I am doing. The longer the run, the greater the speed-up. I'll take a look at those fails and how to improve.

**Comment by swmm-js** [comment]
These errors are caused by low-depth inputs. Pipes with 1-inch or less depth of water can be accommodated for. There are at least 4 options:

- increase table size: this is a terrible option, because only 2.5% of the current table is producing these errors.
- add a secondary/tertiary table: this is a good option.
- revert to original equation: this is an ok option, but removes speed increases for long-running models with low flow.
- add dynamic lookup table: this is a good option.

**Comment by dickinsonre** [comment]
Do you mean the pipes are one inch in diameter?  Or the initial depth is less than 1 inch. 

These errors are caused by low-depth inputs. Pipes with 1-inch or less depth of water can be accommodated for. T

**Comment by dickinsonre** [comment]
These errors are caused by low-depth inputs. Pipes with 1-inch or less depth of water can be accommodated for.   -  **If you have more cross section data points why is this a problem?**

**Comment by swmm-js** [comment]
Robert - I mean flow depths that are less than 1-inch. The power functions begin to vary a lot below 1 inch of flow depth. These values appear to propagate through the model.

Setting a cutoff switch for a foot of flow depth causes the answers to be spot on. 

Setting a cutoff for 1-inch causes the answers to vary in the 1% range. 

I am using the traditional 51-entry shape tables for testing this. The 1.0e-6 tolerance would never allow the higher-definition shapes - the answers are outside of that tolerance.

**Comment by dickinsonre** [comment]
SWMM3, SWMM4 and SWMM5 have the Fudge depth.  Which is really small.  I always liked the fact that SWMM can have lower depths than ICM and Mike Urban.  They have a pretty big min depth which means you have to do a lot of background calcs for volume and water quality modeling to take out the extra flow.  I am sure there is some way on the math verse to have power functions go to zero and be smooth. l

**Comment by swmm-js** [comment]
I've developed an automated table array that increases spread percentage as it approaches lower numbers and builds a varying index. This replicates most of the results using 250 tables of 101 entries each, but I don't think it would get to the 1e-6 requirement. I could trim those tables because it looks like the top end is just doing 0.99999's. This is good enough for internet-based results and would do well as a switch in swmmReact Desktop. I'll see what else I can pull out of the system.

**Comment by LRossman** [comment]
There's no need to provide lookup tables for both` x^(2/3`) and `x^(4/3)` . One only needs a table for `x^(1/3)` since `x^(2/3) = x / x^(1/3)` and `x^(4/3) = x * x^(1/3)`.

**Comment by swmm-js** [comment]
You are right Lew, there isn't a need for both tables, and it turns out, there isn't a need for such a large table group. I was wondering why my table generator went so large, when it matches to 0.000001 long before 250 tables of 101 entries. It turns out, the culprit is in dwflow.c:

    // --- combine terms to find new conduit flow
    denom = 1.0 + dq1 + dq5;
    q = (qOld - dq2 + dq3 + dq4 + dq6) / denom;

The special properties of floating point division and addition cause small differences to mutate over the equation. So even though in dwflow.c:


            dq1 = dt * Conduit[k].roughFactor / pow(rWtd, 1.33333) * fabs(v);

the power function does not effectively reach significant digits of 0.000001 (and lower) for results, any minor changes below that level will still affect the output. This means even a near-exact match (below 0.000001 and relative difference well below 0.01) of return values for a function will cause propagation errors.

**Comment by swmm-js** [comment]
This means for an input of 1.325779 if the tables return a value like 1.456446176, and pow(x, 1.33333) returns 1.456446175, then values like that propagate through the second equation: 

    // --- combine terms to find new conduit flow
    denom = 1.0 + dq1 + dq5;
    q = (qOld - dq2 + dq3 + dq4 + dq6) / denom;

These propagating values cause a huge effect in the 1% range on output of user5.inp, even if all differences are less than 0.0001%. It's not a big deal - users would be horrified to see two systems with differences like these. I'm not going to push it.

**Pull request closed without merging**
