### PR TITLE
Various bug fixes and minor enhancements

### PR DESCRIPTION
**Pull request by cbuahin**
This PR addresses the following issues:

#136 Fix hotstart file 
#109 Fix large numbers in report file
~#70~ Will fix as a minor release update per Michael's recommendation.
#144 Fix elliptical pipe geometry

### CODE REVIEW

**Comment by cbuahin** [comment]
Need to update regression testing files because of change in the constant values.

**Comment by cbuahin** [comment]
@michaeltryby , this is a WIP. I will invite you to review when complete.

**Comment by michaeltryby** [comment]
Sounds good @cbuahin. I will hold any further comment until your PR is ready for review

**Review by michaeltryby — APPROVED** [review]
Looks great. Excellent job @cbuahin!

**Comment by cbuahin** [comment]
Hey @michaeltryby , thanks for taking time to review! I appreciate it.

**Pull request merged**
