### PR TITLE
Seepage fix

### PR DESCRIPTION
**Pull request by LRossman**
Addresses issue #27.

### CODE REVIEW

**Comment by LRossman** [comment]
The build and unit test failed due to:
_WARNING: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured._
@michaeltryby -- can you please look into this.

The build and reg test failed due to different results for test files _user2.inp_ and _user5.inp_ compared to the benchmarks.  Both files have non-zero evaporation rates and open channels and since channel evaporation is treated the same as seepage losses, the fixes made to correctly model these losses will naturally produce different results. Either the benchmark files need to be replaced or the tolerances for acceptable differences need to be relaxed, such as changing the `ATOL_VALUE` in the _run-nrtests.cmd_ file from 1.E-6 to 1.E-4.

**Comment by michaeltryby** [comment]
Thanks @LRossman I will update the benchmark while merging your PR.

**Review by michaeltryby — APPROVED** [review]
I have reviewed the changes and I approve.

**Review by cbuahin — APPROVED** [review]
Looks good to me as well!

**Comment by michaeltryby** [comment]
This PR is ready for merge. Thanks @LRossman for putting it together. And thanks for the review @cbuahin

**Pull request merged**
